# Generated by Django 4.0.5 on 2022-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_autor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ISBN',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
